# Copy this to secrets.toml and add your actual API key
# DO NOT commit the actual secrets.toml file to version control

# Your OpenRouter API Key (Get from https://openrouter.ai/)
OPENROUTER_API_KEY = "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"

# Alternative nested format (optional)
[openrouter]
api_key = "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"
model = "qwen/qwq-32b-preview"
base_url = "https://openrouter.ai/api/v1"

# App configuration
[app]
title = "AI Health Copilot"
version = "1.0.0"
environment = "production"

# Feature flags
[features]
enable_ai_explanations = true
enable_health_plans = true
enable_model_predictions = true

# Security settings
[security]
debug = false
log_level = "INFO"
max_requests_per_hour = 100
