# Streamlit Secrets Configuration
# Replace with your actual OpenRouter API key
# Get your free API key from: https://openrouter.ai/

OPENROUTER_API_KEY = "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"

# Alternative format (both work):
[openrouter]
api_key = "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"

# App configuration
[app]
title = "AI Health Copilot"
version = "1.0.0"
model = "meta-llama/llama-4-maverick-17b-128e-instruct:free"

# Security settings
[security]
debug = false
log_level = "INFO"
