# Streamlit Secrets Configuration
# Replace with your actual OpenRouter API key
# Get your free API key from: https://openrouter.ai/

OPENROUTER_API_KEY = "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"

# Alternative format (both work):
[openrouter]
api_key = "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"

# App configuration
[app]
title = "AI Health Copilot"
version = "1.0.0"
model = "meta-llama/llama-4-maverick-17b-128e-instruct:free"

# Security settings
[security]
debug = false
log_level = "INFO"
